# Assignment 02

Due Sep 6, 11:59pm. Please submit one .ipynb file to Beachboard. 

<p style='text-align: right; '> Hansell Perez </p>
<p style='text-align: right; '> 09/06/2022 </p>

Please go through and study the lecture note [Lec02_numPy.ipynb](https://nbviewer.org/github/huiprobable/MATH578F22CSULB/blob/main/Lectures/Lec02_numPy.ipynb) by yourself, and do the following tasks:

#### You may choose to do five tasks out of seven below. 

1. Reverse a vector. Given a vector, reverse it such that the last element becomes the first, e.g. [1, 2, 3] => [3, 2, 1]

2. Create a 2D array with zeros on the borders and 1 inside.

3. Create a random array with elements [0, 1), then add 10 to all elements in the range [0.2, 0.7).

4. Create a 1D array with 10 random elements. Sort it.

5. For the random array in question 4, instead of sorting it, perform an indirect sort. That is, return the list of indices which would index the array in sorted order.

6. Create a 4x4 array of zeros, and another 4x4 array of ones. Next combine them into a single 8x4 array with the content of the zeros array on top and the ones on the bottom. Finally, do the same, but create a 4x8 array with the zeros on the left and the ones on the right.

7. NumPy functionality Create two 2D arrays and do matrix multiplication first manually (for loop), then using the np.dot function. Use %%timeit to compare execution times. What is happening?

This assignment requires a lot of google search and document reading, to find out suitable functions for different tasks. Please have adquate discussions with each other and with me. 

#### 1. Reverse a vector. Given a vector, reverse it such that the last element becomes the first, e.g. [1, 2, 3] => [3, 2, 1]
For this problem I chose to define the function "reverse_me" which has input "vector", the desired vector to be manipulates, and outputs the desired reversed vector. Note: there is already an existing function, "reverse", that does this same action.

In [37]:
def reverse_me(vector):
    reverse_vector = [0]*len(vector)
    for x in range(len(vector)):
        reverse_vector[x] = vector[len(vector)-(x+1)]
    return(reverse_vector)

In [44]:
vector1 = [1,2,3]
vector2 = ["apple", "banana", "pear"]

In [45]:
print(reverse_me(vector1))
print(reverse_me(vector2))

[3, 2, 1]
['pear', 'banana', 'apple']


#### 2. Create a 2D array with zeros on the borders and 1 inside.
For this exercise I decided to create another function with inputs $m$ and $n$ to specify the dimensions of the array as $m \times n$. Note: if $m,n < 3$, there is no "inside" thus the array produced is filled by zero entries since everything is a "border".

In [74]:
import numpy as np

def zero_border(m,n):
    Array = np.array([[0]*n]*m)
    if m >= 3:
        Array[1:m-1,1:n-1] = 1
    return(Array)

Below you can see a few example of the arrays created by the function defined above.

In [75]:
print(zero_border(2,2))
print(zero_border(3,2))
print(zero_border(2,3))
print(zero_border(5,6))


[[0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]
[[0 0 0]
 [0 0 0]]
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


#### 3. Create a random array with elements [0, 1), then add 10 to all elements in the range [0.2, 0.7).

Below are two examples I tried. I'm not sure what the difference is, although example 1 I believe does not use numpy wheras example 2 does. I think using numpy is better practice but <span style="color: red;"> I would appreciate some feedback.</span>

Ex. 1: uses the append function to insert random values into an empty array of floating data type.

In [94]:
import random
x = array('f',[])
for i in range(10):
    x.append(random.random())
print(x)

array('f', [0.4849344491958618, 0.39080628752708435, 0.3301577866077423, 0.5519107580184937, 0.8641378283500671, 0.41793280839920044, 0.8913429379463196, 0.9241898059844971, 0.20068210363388062, 0.7009581327438354])

In [104]:
for i in range(len(x)):
    if x[i] >= 0.2 and x[i] < 0.7:
        x[i] = x[i] + 10
print(x)

array('f', [10.48493480682373, 10.390806198120117, 10.330158233642578, 10.551910400390625, 0.8641378283500671, 10.417932510375977, 0.8913429379463196, 0.9241898059844971, 10.200681686401367, 0.7009581327438354])


Ex 2: using numpy

In [127]:
import random
y = np.zeros(10)
for i in (range(len(y))):
    y[i] = random.random()
y

array([0.2760938 , 0.54243138, 0.14264671, 0.35843006, 0.04034348,
       0.03638176, 0.27923123, 0.17680544, 0.17626384, 0.95911504])

In [129]:
for i in range(len(x)):
    if y[i] >= 0.2 and x[i] < 0.7:
        y[i] = y[i] + 10
print(y)

[10.2760938  10.54243138  0.14264671 10.35843006  0.04034348  0.03638176
 10.27923123  0.17680544  0.17626384 10.95911504]


#### 4. Create a 1D array with 10 random elements. Sort it.
I will use the same array as in Ex. 2 above and the numpy function "sort".

In [147]:
print(y)
np.sort(y)

[10.2760938  10.54243138  0.14264671 10.35843006  0.04034348  0.03638176
 10.27923123  0.17680544  0.17626384 10.95911504]


array([ 0.03638176,  0.04034348,  0.14264671,  0.17626384,  0.17680544,
       10.2760938 , 10.27923123, 10.35843006, 10.54243138, 10.95911504])

#### 6. Create a 4x4 array of zeros, and another 4x4 array of ones. Next combine them into a single 8x4 array with the content of the zeros array on top and the ones on the bottom. Finally, do the same, but create a 4x8 array with the zeros on the left and the ones on the right.


In [137]:
array1 = np.array([[0]*4]*4)
print(array1)
array2 = np.array([[1]*4]*4)
print(array2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [140]:
vertical = np.vstack((array1,array2))
print(vertical)
horizontal = np.hstack((array1,array2))
print(horizontal)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1]]
