# Assignment 05

Due Oct 20, 11:59pm. Please submit one .ipynb file to Beachboard. 

<p style='text-align: right; '> Hansell Perez </p>
<p style='text-align: right; '> October 20, 2022 </p>

Please implement the LU factorization scheme, then construct two examples to show the accuracy of the factorization. 

<div style="background-color:rgba(0, 0, 0, 0.0470588); padding:10px 0;font-family:monospace;">
This is pseudocode for <font color = "red">LU factorization</font><br><hr/><br>
rows, cols = A.shape <br>
for i in range(rows):<br>
&nbsp;&nbsp;&nbsp;&nbsp; $L[i+1:rows,i]=\dfrac{U[i+1:rows,i]}{U[i,i]}$<br>
&nbsp;&nbsp;&nbsp;&nbsp; $U[i+1:rows,i:cols] -= L[i+1:rows,i]\times U[i,i:cols]$ <font color = "green"># $\times$ is for outer product</font><br>
&nbsp;&nbsp;&nbsp;&nbsp; $U[i+1:rows,i] = 0$<br>
</div>


This pseudocode may not be exactly correct, and it may lack some steps. It's just for reference. 

In [94]:
import numpy as np
import random

In [89]:
def LU_decomp(A):
    rows, cols = A.shape
    if (rows != cols):
        print("Matrix provided is not square.")
        return
    else:
        L = np.identity(rows)
        U = np.array(np.zeros(rows*cols)).reshape(rows, cols)
        
        for i in range(rows):
            for j in range(i, cols):
                if (i==0):
                    U[i][j] = A[i][j]
                else:
                    sum = 0
                    for k in range(i):
                        sum += (L[i][k]*U[k][j])
                    U[i][j] = A[i][j] - sum
        
            for j in range(i):
                if (j==0):
                    L[i][j] = A[i][j]/U[j][j]
                else:
                    sum = 0
                    for k in range(i):
                        sum += (L[i][k]*U[k][j])
                    L[i][j] = (A[i][j] - sum)/U[i][i]
    return L, U
    

In [ ]:
different approach

In [113]:
MAX = 100
 
 
def luDecomposition(mat, n):
 
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]
 
    # Decomposing matrix into Upper
    # and Lower triangular matrix
    for i in range(n):
 
        # Upper Triangular
        for k in range(i, n):
 
            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
 
            # Evaluating U(i, k)
            upper[i][k] = mat[i][k] - sum
 
        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:
 
                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
 
                # Evaluating L(k, i)
                lower[k][i] = int((mat[k][i] - sum) /
                                  upper[i][i])
 
    # setw is for displaying nicely
    print("Lower Triangular\t\tUpper Triangular")
 
    # Displaying the result :
    for i in range(n):
 
        # Lower
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")
 
        # Upper
        for j in range(n):
            print(upper[i][j], end="\t")
        print("")

In [98]:
mat1 = [[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]]
mat2 = np.random.randint(1,10,size=(6,6))


In [92]:
L,U = LU_decomp(np.array(mat1))
L,U,L@U

(array([[ 1. ,  0. ,  0. ],
        [-2. ,  1. ,  0. ],
        [-2. , -0.5,  1. ]]),
 array([[ 2., -1., -2.],
        [ 0.,  6.,  3.],
        [ 0.,  0.,  8.]]),
 array([[ 2. , -1. , -2. ],
        [-4. ,  8. ,  7. ],
        [-4. , -1. , 10.5]]))

In [112]:
luDecomposition(mat1, 3)

Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2.0	1	0		0	4.0	-1.0	
-2.0	-1.0	1		0	0	3.0	


In [99]:
L,U = LU_decomp(np.array(mat2))
L,U,L@U

(array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.00000000e-01,  1.00000000e+00,  1.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 7.50000000e-01,  1.16666667e+00, -2.75000000e+00,
          1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  1.11111111e-01, -7.40740741e-02,
         -1.89300412e-01,  1.00000000e+00,  0.00000000e+00],
        [ 7.50000000e-01, -5.00000000e-01,  5.75000000e+00,
         -3.57500000e+01,  1.40250000e+02,  1.00000000e+00]]),
 array([[8., 2., 3., 6., 6., 9.],
        [0., 7., 6., 2., 6., 6.],
        [0., 0., 1., 7., 8., 4.],
        [0., 0., 0., 3., 5., 4.],
        [0., 0., 0., 0., 9., 8.],
        [0., 0., 0., 0., 0., 1.]]),
 array([[   8.        ,    2.        ,    3.        ,    6.       

In [104]:
def LU_decomp(A):
    rows, cols = A.shape
    if (rows != cols):
        print("Matrix provided is not square.")
        return
    else:
        L = np.identity(rows)
        U = np.array(np.zeros(rows*cols)).reshape(rows, cols)
        
        
        U[0] = A[0]
        for i in range(rows):
            L[i][0] = A[i][0]/U[0][0]
            
        for i in range(1, rows):
            for j in range(i, cols):
                sum = 0
                for k in range(i):
                    sum += (L[i][k]*U[k][j])
                U[i][j] = A[i][j] - sum
        
            for j in range(i):
                if (j==0):
                    L[i][j] = A[i][j]/U[j][j]
                else:
                    sum = 0
                    for k in range(i):
                        sum += (L[i][k]*U[k][j])
                    L[i][j] = (A[i][j] - sum)/U[i][i]
    return L, U
    

In [108]:
L,U = LU_decomp(np.array(mat2))
L,U

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.5       , -2.        ,  1.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.75      , -2.33333333, -3.83333333,  1.        ,  0.        ,
          0.        ],
        [ 1.        ,  0.33333333, -0.33333333,  0.22222222,  1.        ,
          0.        ],
        [ 0.75      ,  0.08695652, -0.43289225, -0.97032958, -1.24341322,
          1.        ]]),
 array([[ 8.  ,  2.  ,  3.  ,  6.  ,  6.  ,  9.  ],
        [ 0.  ,  5.  ,  3.  , -4.  ,  0.  , -3.  ],
        [ 0.  ,  0.  , -0.5 ,  4.  ,  5.  , -0.5 ],
        [ 0.  ,  0.  ,  0.  , -1.5 ,  0.5 , -2.75],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  3.  , -1.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , -5.75]]))

In [109]:
L@U

array([[  8.        ,   2.        ,   3.        ,   6.        ,
          6.        ,   9.        ],
       [  8.        ,   7.        ,   6.        ,   2.        ,
          6.        ,   6.        ],
       [  4.        ,  -9.        ,  -5.        ,  15.        ,
          8.        ,  10.        ],
       [  6.        , -10.16666667,  -2.83333333,  -3.        ,
        -14.16666667,  12.91666667],
       [  8.        ,   3.66666667,   4.16666667,   3.        ,
          7.44444444,   6.55555556],
       [  6.        ,   1.93478261,   2.72731569,   3.87609928,
         -1.87986571,   4.86739613]])

In [110]:
mat2

array([[8, 2, 3, 6, 6, 9],
       [8, 7, 6, 2, 6, 6],
       [4, 2, 1, 7, 8, 4],
       [6, 5, 1, 3, 5, 4],
       [8, 3, 3, 4, 9, 8],
       [6, 1, 5, 8, 9, 1]])