# Assignment 6 (Due on Dec 1st, midnight. Enjoy!)
Hansell Perez

This will be the very last homework.

1. Implement pure QR algorithm, practical QR algorithm to find eigenvalues of A. Just find three largest eigenvalues and their corresponding eigenvectors. 
2. Implement Alnoldi algorithm for obtaining the Hessenberg matrix $H$. Then use practical QR algorithm to transform $H$ into an upper triangular matrix. Then find the three largest eigenvales and their corresponding eigenvectors. 

* Please design a $10\times 10$ random matrix, and make it symmetric. Then find the eigenvalues and eigenvectors using the functions you implemented. After that, use *numpy.linalg.eig* to check against the correctness of your eigenvalue and eigenvector calculation.  
* Notice that the pure QR algorithm and the Alnoldi algorithm are already implemented in the lecture notes on Page Rank. 
* You may refer to the Lecture notes for Lecture 23, posted in Beachboard as [Eigen_QR.pdf](https://bbcsulb.desire2learn.com/d2l/le/lessons/882936/topics/10518848), for theoretical details on obtaining more than one eigenvalues and eigenvectors. 
* **You do not need to submit all of these.** To not create too much work and ruin your Thanksgiving break, I would like you to **submit only** the implementation practical QR algorithm, and using it to find **one** largest eigenvalue and the corresponding eigenvector. 

### Pure QR Algorithm

In [103]:
def pure_qr(A, max_iter=50000):
    Ak = np.copy(A)
    n = A.shape[0]
    QQ = np.eye(n)
    for k in range(max_iter):
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
        QQ = QQ @ Q
        if k % 100 == 0:
            print(Ak)
            print("\n")
    return Ak, QQ

### Practical QR Algorithm

In [104]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import qr

def practical_qr(A, max_iter=5000):
    Ak = np.copy(A)
    n = A.shape[0]
    I = np.eye(n)
    for k in range(max_iter):
        sk, vk = eig(Ak[n-3:n-1,n-3:n-1])
        Qk, Rk = np.linalg.qr(Ak - min(sk)*I)
        Ak = Rk @ Qk + min(sk)*I
        if k % 100 == 0:
            print(Ak)
            print("\n")
    return Ak, Qk

Generate random matrix

In [105]:
n = 6
A = np.random.rand(n,n)
AT = A @ A.T

Implement Practical QR Algorithm

In [106]:
Ak, Q = practical_qr(A)

[[ 2.45915684  0.38176752 -0.07767492  1.26596231 -0.45118349  0.07432341]
 [-0.49760228 -0.15120383  0.33756019 -0.2778169  -0.00848191  0.22892681]
 [ 0.19899352 -0.19578549  0.13737184  0.6673128   0.22125989  0.23847449]
 [ 0.90476416 -0.85450146 -0.15838426 -0.21762498 -0.34129822 -0.06323673]
 [ 0.2402327  -0.17618756 -0.10524523 -0.13725346 -0.1091598   0.21153415]
 [ 0.14453329 -0.11516042  0.11842678 -0.08981962  0.17151913 -0.18137579]]


[[ 2.76988520e+000  2.89923724e-001  3.76737548e-001  7.67377692e-001
   3.76209012e-002  6.78733769e-001]
 [-2.53440967e-057  1.28958410e-001  6.05392665e-001  3.07590328e-001
  -6.19682355e-002 -2.93787358e-001]
 [ 1.39815261e-057 -4.26491381e-001  1.42964444e-001 -1.33701595e-003
   3.33781799e-001  5.42355237e-001]
 [ 2.17015780e-064 -1.55486898e-007 -7.91852285e-008  1.80991459e-001
   6.89688603e-002  3.92247142e-002]
 [-3.45500224e-134  8.02130875e-078  1.39739411e-077  1.35464835e-071
  -5.19001352e-001 -6.09276381e-002]
 [-2.8511881

  -4.28637676e-001 -7.66633903e-001]]


[[ 2.76988520e+000 -8.69138947e-002 -4.67368261e-001  7.67377581e-001
   3.76209012e-002  6.78733769e-001]
 [ 0.00000000e+000  5.94028925e-002  5.62731648e-001 -2.74560731e-001
   2.06963636e-001  5.08270839e-001]
 [ 0.00000000e+000 -4.69152513e-001  2.12519928e-001 -1.38671765e-001
  -2.69102997e-001 -3.49458135e-001]
 [ 0.00000000e+000 -3.51762920e-153 -1.10701760e-153  1.80991493e-001
   6.89687276e-002  3.92244779e-002]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
  -5.19001352e-001 -6.09276381e-002]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
  -4.28637676e-001 -7.66633903e-001]]


[[ 2.76988520e+000  4.24592118e-001  2.13795813e-001  7.67377581e-001
   3.76209012e-002  6.78733769e-001]
 [ 0.00000000e+000  2.01484318e-001  5.77238238e-001  2.76599666e-001
   8.88676727e-002 -2.96061509e-002]
 [ 0.00000000e+000 -4.54645924e-001  7.04385026e-002 -1.34558828e-001
   3.27647534e-001  6.16103652e

[[ 2.76988520e+000  4.60486940e-001  1.18063096e-001  7.67377581e-001
   3.76209012e-002  6.78733769e-001]
 [ 0.00000000e+000  2.21099750e-001  5.44260510e-001  2.41430574e-001
   1.56871334e-001  1.02816460e-001]
 [ 0.00000000e+000 -4.87623652e-001  5.08230707e-002 -1.90590481e-001
   3.01067691e-001  6.08185013e-001]
 [ 0.00000000e+000 -5.26699072e-226 -3.34130692e-226  1.80991493e-001
   6.89687276e-002  3.92244779e-002]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
  -5.19001352e-001 -6.09276381e-002]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
  -4.28637676e-001 -7.66633903e-001]]


[[ 2.76988520e+000 -2.80742800e-001  3.83628202e-001  7.67377581e-001
   3.76209012e-002  6.78733769e-001]
 [ 0.00000000e+000  9.38821724e-002  4.36696841e-001  8.72142539e-002
  -3.37803992e-001 -6.02835510e-001]
 [ 0.00000000e+000 -5.95187321e-001  1.78040648e-001  2.94969706e-001
   3.37465957e-002 -1.30574045e-001]
 [ 0.00000000e+000 -1.45312489e-23

Check that Q is orthogonal

In [107]:
np.allclose(np.eye(n), Q @ Q.T), np.allclose(np.eye(n), Q.T @ Q)

(True, True)

The largest eigenvalue of the matrix A is given by the first entry of Ak

In [108]:
Ak[0,0]

2.7698852035658925

Compute the eigenvalues of A

In [109]:
np.linalg.eigvals(A)

array([ 2.7698852 +0.j        ,  0.13596141+0.50808047j,
        0.13596141-0.50808047j,  0.18099149+0.j        ,
       -0.8464014 +0.j        , -0.43923386+0.j        ])

Compute the eigenvector of the largest eigenvalue

In [110]:
e_val,e_vec = eig(A)

In [111]:
e_val[0],e_vec[0]

((2.769885203565891+0j),
 array([ 0.37793378+0.j,  0.64653129+0.j,  0.64653129-0.j, -0.1453599 +0.j,
        -0.36734452+0.j, -0.20248128+0.j]))